# Generated by Django 3.2.3 on 2021-05-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.PositiveIntegerField(default=0, help_text='Цена', verbose_name='Цена ремонта')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Стоимость ремонта',
            },
        ),
        migrations.CreateModel(
            name='Sail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sail', models.PositiveIntegerField(default=0, help_text='Цена', verbose_name='Цена продажи')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Стоимость продажи',
            },
        ),
        migrations.CreateModel(
            name='SkladAvto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование склада')),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='SkladZap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование склада')),
                ('zap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uslugi.zapas', verbose_name='Запасные части')),
            ],
            options={
                'verbose_name': 'Склад запчастей',
                'verbose_name_plural': 'Склады запчастей',
            },
        ),
    ]
