# Generated by Django 3.2.3 on 2021-05-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название центра')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uslugi.repair', verbose_name='Стоимость ремонта')),
                ('sail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uslugi.sail', verbose_name='Стоимость продажи')),
                ('sklad_avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uslugi.skladavto', verbose_name='Склад авто')),
                ('sklad_zap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uslugi.skladzap', verbose_name='Склад запчастей')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
