# Generated by Django 3.2.3 on 2021-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0004_auto_20210531_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skladavto',
            options={'verbose_name': 'Склад авто', 'verbose_name_plural': 'Склады авто'},
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='zapas',
        ),
        migrations.AddField(
            model_name='zapas',
            name='zapas',
            field=models.ManyToManyField(to='uslugi.SkladZap', verbose_name='Запасные части'),
        ),
    ]
