# Generated by Django 3.2.3 on 2021-05-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Modl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Авто')),
                ('vin', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='VIN')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.color', verbose_name='Цвет')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.mark', verbose_name='Марка')),
                ('modl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.modl', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
