# Generated by Django 3.2.4 on 2021-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210613_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='VIN'),
        ),
    ]
