# Generated by Django 3.2.4 on 2021-06-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210613_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Car',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Авто')),
                ('vin', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='VIN')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.color', verbose_name='Цвет')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.mark', verbose_name='Марка')),
                ('modl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.modl', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомн',
            },
        ),
    ]
