# Generated by Django 3.2.3 on 2021-05-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealcent', '0002_auto_20210530_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название центра')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
    ]
